#!/usr/bin/env bash

# Reload .bash_profile or zshrc
alias rebash="source ~/.bash_profile"
alias rezsh="source ~/.zshrc"

# Finder
alias f="open ."

# Lock the screen (when going AFK)
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

# IP addresses
alias iplocal="ipconfig getifaddr en0"

# Directory listings
# LS_COLORS='no=01;37:fi=01;37:di=07;96:ln=01;36:pi=01;32:so=01;35:do=01;35:bd=01;33:cd=01;33:ex=01;31:mi=00;05;37:or=00;05;37:'
# -G Add colors to ls
# -l Long format
# -h Short size suffixes (B, K, M, G, P)
# -p Postpend slash to folders
alias ls='ls -G -h -p -a'
alias ll='ls -l -G -h -p -a'

