#!/usr/bin/env bash

#########################################################
# VARIABLES
#########################################################
# Colors for information
YELLOWB="\033[1;33m"
NONE="\033[0m"

# Variables
DOTFILES_DIR=$(cd $(dirname -- $(readlink ~/.bash_profile))/../; pwd -P)
CONFIG_DIR="${DOTFILES_DIR}/config"

#########################################################
# TEMPLATE GENERATION
# all generation functions start with 'gen'
#########################################################


