#!/usr/bin/env bash

#Git aliases
alias gt="git tag -l"
alias gtd="git tag -d $1"
alias gcall="git add -A && git commit -m"

#Git functions
function co() {
  if [ -z "$1" ]; then
    RESET='\033[0m'
    GREEN='\033[0;32m'
    CYAN='\033[0;36m'
    YELLOW='\e[33m'
    git fetch > /dev/null;
    local branches=$(git for-each-ref --sort=-committerdate --format="%(HEAD) $CYAN %(refname:short) $RESET- %(authorname) ($GREEN %(committerdate:relative)$RESET)" refs/heads)
    local remotes=$(git for-each-ref --sort=-committerdate --format="%(HEAD) $YELLOW %(refname:short) $RESET- %(authorname) ($GREEN %(committerdate:relative)$RESET)" refs/remotes)
    local target=$( ( echo "$remotes"; echo "$branches";) | fzf --ansi --tac | cut -c4- | awk '{print $1}' | cut -d'/' -f2 )
    if [ -n "$target" ]; then
      echo "Checking out $target"
      git checkout "$target"
    fi
  else
    git checkout $1
  fi
}